name       : libopenshot-audio
version    : 0.1.6
release    : 4
source     :
    - https://github.com/OpenShot/libopenshot-audio/archive/v0.1.6.tar.gz : 090ed62a59f35642081f6da58677e5f8f316ed2062cb47cf0617a71678b890c3
license    : GPL-3.0-or-later
component  : multimedia.library
summary    : A high-quality audio editing and playback library used by libopenshot.
description: |
    A high-quality audio editing and playback library used by libopenshot.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - doxygen
setup      : |
    %cmake -DLIB_SUFFIX=%LIBSUFFIX% .
build      : |
    %make
install    : |
    %make_install
