name       : libopenshot-audio
version    : 0.1.4
release    : 2
source     :
    - https://launchpad.net/libopenshot/0.1/0.1.6/+download/libopenshot-audio-0.1.4.tar.gz : 81108fa305fbfe63ab1f490091ae651e8b4c571cd0ce7cbb832db306ed85124f
license    : GPL-3.0
component  : multimedia.library
summary    : A high-quality audio editing and playback library used by libopenshot.
description: |
    A high-quality audio editing and playback library used by libopenshot.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - doxygen
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
