name       : libopenshot-audio
version    : 0.1.2
release    : 1
source     :
    - https://launchpad.net/libopenshot/0.1/0.1.4/+download/libopenshot-audio-0.1.2.tar.gz : ec587ceed6b8d0d8de455b222fdb75832e67779e1a7b80925e86709353099e8a
license    : GPL-3.0
component  : multimedia.library
summary    : A high-quality audio editing and playback library used by libopenshot.
description: |
    A high-quality audio editing and playback library used by libopenshot.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - doxygen
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
