name       : libopenshot-audio
version    : 0.2.0
release    : 10
source     :
    - https://github.com/OpenShot/libopenshot-audio/archive/v0.2.0.tar.gz : 937ff4f1c2dfb8ab5d56ad85beacaa29dfd5a79af0d9cf647386034fe9882309
license    : GPL-3.0-or-later
component  : multimedia.library
summary    : A high-quality audio editing and playback library used by libopenshot.
description: |
    A high-quality audio editing and playback library used by libopenshot.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - doxygen
setup      : |
    %cmake_ninja -DLIB_SUFFIX=%LIBSUFFIX% .
build      : |
    %ninja_build
install    : |
    %ninja_install
