name       : libopenshot-audio
version    : 0.2.2
release    : 12
source     :
    - https://github.com/OpenShot/libopenshot-audio/archive/v0.2.2.tar.gz : 66bedfda0d8d430598b21bc2dde6c0016a758a6c83467d0273a9d692de10baaf
license    : GPL-3.0-or-later
component  : multimedia.library
summary    : A high-quality audio editing and playback library used by libopenshot.
description: |
    A high-quality audio editing and playback library used by libopenshot.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - doxygen
setup      : |
    %cmake_ninja -DLIB_SUFFIX=%LIBSUFFIX% .
build      : |
    %ninja_build
install    : |
    %ninja_install
