name       : libopenshot-audio
version    : 0.1.7
release    : 5
source     :
    - https://github.com/OpenShot/libopenshot-audio/archive/v0.1.7.tar.gz : 3aa6dcfc5caaa409cfa63db206d3f6f7e25854642e796915e9ac8fdf9dbc9a3f
license    : GPL-3.0-or-later
component  : multimedia.library
summary    : A high-quality audio editing and playback library used by libopenshot.
description: |
    A high-quality audio editing and playback library used by libopenshot.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - doxygen
setup      : |
    %cmake -DLIB_SUFFIX=%LIBSUFFIX% .
build      : |
    %make
install    : |
    %make_install
