name       : libopenshot-audio
version    : 0.1.9
release    : 8
source     :
    - https://github.com/OpenShot/libopenshot-audio/archive/v0.1.9.tar.gz : 818708988758a6bdf625472f6b420c42cca2df73362ef0566006cf7af983da96
license    : GPL-3.0-or-later
component  : multimedia.library
summary    : A high-quality audio editing and playback library used by libopenshot.
description: |
    A high-quality audio editing and playback library used by libopenshot.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - doxygen
setup      : |
    %cmake_ninja -DLIB_SUFFIX=%LIBSUFFIX% .
build      : |
    %ninja_build
install    : |
    %ninja_install
