name       : libopenshot-audio
version    : 0.1.8
release    : 7
source     :
    - https://github.com/OpenShot/libopenshot-audio/archive/v0.1.8.tar.gz : 384d0ef39c78f16d77048de3c96152321724084f978dc622675dd6bb16e15e19
    - https://patch-diff.githubusercontent.com/raw/OpenShot/libopenshot-audio/pull/39.patch : ae784a96730f7cf09ba7bf29d06704ba6a0eca662d242d786b0a86a4343e9dc9
license    : GPL-3.0-or-later
component  : multimedia.library
summary    : A high-quality audio editing and playback library used by libopenshot.
description: |
    A high-quality audio editing and playback library used by libopenshot.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - doxygen
setup      : |
    %patch -p1 -i $sources/39.patch
    %cmake -DLIB_SUFFIX=%LIBSUFFIX% .
build      : |
    %make
install    : |
    %make_install
